name: .NET Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Publish Windows
      run: dotnet publish -c Release -r win-x64 --self-contained
    - name: Publish OSX
      run: dotnet publish -c Release -r osx-x64 --self-contained
    - name: Publish Linux
      run: dotnet publish -c Release -r linux-x64 --self-contained